server:
  ssl:
#    protocol: tls
#    enabled-protocols: TLSV1.2
    enable: true
    key-alias: spring-tls
    key-store: classpath:certs/keystore.p12
    key-store-type: PKCS12
    key-store-password: changeit
  port: 8888



